---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.burban.me
  resources:
  - ingresshandlings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.burban.me
  resources:
  - ingresshandlings/finalizers
  verbs:
  - update
- apiGroups:
  - networking.burban.me
  resources:
  - ingresshandlings/status
  verbs:
  - get
  - patch
  - update
